#ifndef CAMERASYMBOL_H
#define CAMERASYMBOL_H

// Created with the CIM symbol builder tool: https://esri.github.io/cim-symbol-builder-js/
// And this MIT-licensed icon: https://www.iconfinder.com/icons/211634/camera_icon
constexpr const char *c_cameraCimSymbol = R"({
  "type": "CIMPointSymbol",
  "symbolLayers": [
    {
      "type": "CIMVectorMarker",
      "enable": true,
      "anchorPointUnits": "Relative",
      "dominantSizeAxis3D": "Z",
      "size": 20,
      "billboardMode3D": "FaceNearPlane",
      "frame": {
        "xmin": 0,
        "ymin": 0,
        "xmax": 512,
        "ymax": 512
      },
      "markerGraphics": [
        {
          "type": "CIMMarkerGraphic",
          "geometry": {
            "rings": [
              [
                [
                  424,
                  312
                ],
                [
                  414,
                  316
                ],
                [
                  410,
                  326
                ],
                [
                  414,
                  336
                ],
                [
                  424,
                  340
                ],
                [
                  434,
                  336
                ],
                [
                  438,
                  326
                ],
                [
                  434,
                  316
                ],
                [
                  424,
                  312
                ]
              ],
              [
                [
                  256,
                  147
                ],
                [
                  238,
                  148
                ],
                [
                  221,
                  154
                ],
                [
                  205,
                  162
                ],
                [
                  191,
                  174
                ],
                [
                  179,
                  188
                ],
                [
                  171,
                  204
                ],
                [
                  165,
                  221
                ],
                [
                  164,
                  239
                ],
                [
                  165,
                  257
                ],
                [
                  171,
                  274
                ],
                [
                  179,
                  290
                ],
                [
                  191,
                  305
                ],
                [
                  205,
                  316
                ],
                [
                  221,
                  325
                ],
                [
                  238,
                  330
                ],
                [
                  256,
                  332
                ],
                [
                  274,
                  330
                ],
                [
                  291,
                  325
                ],
                [
                  307,
                  316
                ],
                [
                  321,
                  305
                ],
                [
                  333,
                  290
                ],
                [
                  341,
                  274
                ],
                [
                  347,
                  257
                ],
                [
                  348,
                  239
                ],
                [
                  347,
                  221
                ],
                [
                  341,
                  204
                ],
                [
                  333,
                  188
                ],
                [
                  321,
                  174
                ],
                [
                  307,
                  162
                ],
                [
                  291,
                  154
                ],
                [
                  274,
                  148
                ],
                [
                  256,
                  147
                ]
              ],
              [
                [
                  430,
                  96
                ],
                [
                  443,
                  99
                ],
                [
                  454,
                  106
                ],
                [
                  461,
                  117
                ],
                [
                  464,
                  130
                ],
                [
                  464,
                  332
                ],
                [
                  461,
                  345
                ],
                [
                  454,
                  355
                ],
                [
                  443,
                  362
                ],
                [
                  430,
                  365
                ],
                [
                  363,
                  365
                ],
                [
                  322,
                  406
                ],
                [
                  322,
                  406
                ],
                [
                  322,
                  406
                ],
                [
                  311,
                  413
                ],
                [
                  299,
                  416
                ],
                [
                  215,
                  416
                ],
                [
                  201,
                  413
                ],
                [
                  190,
                  405
                ],
                [
                  190,
                  405
                ],
                [
                  151,
                  365
                ],
                [
                  82,
                  365
                ],
                [
                  69,
                  362
                ],
                [
                  58,
                  355
                ],
                [
                  51,
                  345
                ],
                [
                  48,
                  332
                ],
                [
                  48,
                  130
                ],
                [
                  51,
                  117
                ],
                [
                  58,
                  106
                ],
                [
                  69,
                  99
                ],
                [
                  82,
                  96
                ],
                [
                  430,
                  96
                ]
              ]
            ]
          },
          "symbol": {
            "type": "CIMPolygonSymbol",
            "symbolLayers": [
              {
                "type": "CIMSolidFill",
                "enable": true,
                "color": [
                  0,
                  0,
                  0,
                  255
                ]
              }
            ],
            "angleAlignment": "Map"
          }
        },
        {
          "type": "CIMMarkerGraphic",
          "geometry": {
            "rings": [
              [
                [
                  256,
                  169.1
                ],
                [
                  269.6,
                  170.4
                ],
                [
                  282.7,
                  174.4
                ],
                [
                  294.8,
                  180.9
                ],
                [
                  305.4,
                  189.6
                ],
                [
                  314.1,
                  200.2
                ],
                [
                  320.5,
                  212.3
                ],
                [
                  324.5,
                  225.4
                ],
                [
                  325.8,
                  239.1
                ],
                [
                  324.5,
                  252.8
                ],
                [
                  320.5,
                  265.9
                ],
                [
                  314.1,
                  278
                ],
                [
                  305.4,
                  288.6
                ],
                [
                  294.8,
                  297.3
                ],
                [
                  282.7,
                  303.8
                ],
                [
                  269.6,
                  307.8
                ],
                [
                  256,
                  309.1
                ],
                [
                  242.4,
                  307.8
                ],
                [
                  229.3,
                  303.8
                ],
                [
                  217.2,
                  297.3
                ],
                [
                  206.6,
                  288.6
                ],
                [
                  197.9,
                  278
                ],
                [
                  191.5,
                  265.9
                ],
                [
                  187.5,
                  252.8
                ],
                [
                  186.2,
                  239.1
                ],
                [
                  187.5,
                  225.4
                ],
                [
                  191.5,
                  212.3
                ],
                [
                  197.9,
                  200.2
                ],
                [
                  206.7,
                  189.6
                ],
                [
                  217.3,
                  180.9
                ],
                [
                  229.3,
                  174.4
                ],
                [
                  242.4,
                  170.4
                ],
                [
                  256,
                  169.1
                ]
              ]
            ]
          },
          "symbol": {
            "type": "CIMPolygonSymbol",
            "symbolLayers": [
              {
                "type": "CIMSolidFill",
                "enable": true,
                "color": [
                  0,
                  0,
                  0,
                  255
                ]
              }
            ],
            "angleAlignment": "Map"
          }
        }
      ],
      "scaleSymbolsProportionally": true,
      "respectFrame": true,
      "clippingPath": {
        "type": "CIMClippingPath",
        "clippingType": "Intersect",
        "path": {
          "rings": [
            [
              [
                0,
                0
              ],
              [
                512,
                0
              ],
              [
                512,
                512
              ],
              [
                0,
                512
              ],
              [
                0,
                0
              ]
            ]
          ]
        }
      }
    }
  ],
  "animations": []
})";

#endif // CAMERASYMBOL_H
